### ISSUE TITLE
About auto depths = points.norm(2, 1, true);

### ISSUE THREAD

**Issue by zhSlamer** [HITSZ-NRSL/RIM#1]
Thank you for your wonderful work!

I meet this problem when running code at begin;
in neural_slam.cpp  line 416 in norm : auto depths = points.norm(2, 1, true);
I want to ask for help to solve this.
![2024-03-09 14-16-38 的屏幕截图](https://github.com/HITSZ-NRSL/RIM/assets/68368006/328bbc41-1d56-4dcc-8a77-4914d3c96dcb)

Thank you!

**Comment by jianhengLiu** [comment]
Sorry for late response!

Can you give me a brief instruction to reproduce this error?
You could also add `CUDA_LAUNCH_BLOCKING=1 ` before your command for a specific error position.

Thanks!

**Comment by zhSlamer** [comment]
Maybe this reason ：
I want to run Kitti0 dataset,  so it cannot run function [ get_input() and get_next_data  ]from points.bin, so occur this problem that points are None; Because it only support .ply format.

So how to config it to run kitti0

Thank you very much!

**Comment by jianhengLiu** [comment]
Oh, sorry!
It only supports .ply format point cloud so far.
You might first convert them into .ply and run.
When I have time later, I will update the code or a converting script.
Thanks!

**Comment by zhSlamer** [comment]
OK
Thank you!
